# Generated by Django 4.2.18 on 2025-02-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio_app', '0003_alter_article_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'мои проект', 'verbose_name_plural': 'мои проекты'},
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='изображение'),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='изображение'),
        ),
    ]
