# Generated by Django 4.2.18 on 2025-02-25 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio_app', '0004_alter_project_options_article_image_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
